INCLUDEPATH += \
    $$PWD/../../external \
    $$PWD/../../external/chipmunk/include/chipmunk \
    $$PWD/../../CocosDenshion/include \
    $$PWD/../../cocos2dx/include \
    $$PWD/../../cocos2dx/platform \ 
    $$PWD/../../cocos2dx/platform/qt \
    $$PWD/../../cocos2dx/kazmath/include \
    $$PWD/../../cocos2dx/cocoa \
    $$PWD/../../cocos2dx \
    $$PWD/.. \
    $$PWD/../AssetsManager \
    $$PWD/../CCBReader \
    $$PWD/../CocoStudio/Action \
    $$PWD/../CocoStudio/Armature \
    $$PWD/../CocoStudio/Armature/animation \
    $$PWD/../CocoStudio/Armature/datas \
    $$PWD/../CocoStudio/Armature/display \
    $$PWD/../CocoStudio/Armature/external_tool \
    $$PWD/../CocoStudio/Armature/physics \
    $$PWD/../CocoStudio/Armature/utils \
    $$PWD/../CocoStudio/Components \
    $$PWD/../CocoStudio/GUI/BaseClasses \
    $$PWD/../CocoStudio/GUI/Layouts \
    $$PWD/../CocoStudio/GUI/System \
    $$PWD/../CocoStudio/GUI/UIWidgets \
    $$PWD/../CocoStudio/Json \
    $$PWD/../CocoStudio/Json/lib_json \
    $$PWD/../CocoStudio/Reader \
    $$PWD/../GUI/CCControlExtension \
    $$PWD/../GUI/CCEditBox \
    $$PWD/../GUI/CCScrollView \
    $$PWD/../LocalStorage \
    $$PWD/../network \
    $$PWD/../physics_nodes \ 
    $$PWD/../spine \    
    $$PWD/../../cocos2dx/platform/third_party/qt/curl

!contains(DEFINES,DONT_INCLUDE_EXTENSION_SOURCES) {
contains(DEFINES,COCOS2DXQT_LIBRARY) {
HEADERS += \
    $$PWD/../AssetsManager/AssetsManager.h \
    $$PWD/../CocoStudio/Armature/animation/CCArmatureAnimation.h  \
    $$PWD/../CocoStudio/Armature/animation/CCProcessBase.h  \
    $$PWD/../CocoStudio/Armature/animation/CCTween.h  \
    $$PWD/../CocoStudio/Armature/datas/CCDatas.h  \
    $$PWD/../CocoStudio/Armature/display/CCBatchNode.h  \
    $$PWD/../CocoStudio/Armature/display/CCDecorativeDisplay.h  \
    $$PWD/../CocoStudio/Armature/display/CCDisplayFactory.h  \
    $$PWD/../CocoStudio/Armature/display/CCDisplayManager.h  \
    $$PWD/../CocoStudio/Armature/display/CCSkin.h  \
    $$PWD/../CocoStudio/Armature/external_tool/sigslot.h  \
    $$PWD/../CocoStudio/Armature/physics/CCColliderDetector.h  \
    $$PWD/../CocoStudio/Armature/utils/CCArmatureDataManager.h  \
    $$PWD/../CocoStudio/Armature/utils/CCArmatureDefine.h  \
    $$PWD/../CocoStudio/Armature/utils/CCDataReaderHelper.h  \
    $$PWD/../CocoStudio/Armature/utils/CCSpriteFrameCacheHelper.h  \
    $$PWD/../CocoStudio/Armature/utils/CCTransformHelp.h  \
    $$PWD/../CocoStudio/Armature/utils/CCTweenFunction.h  \
    $$PWD/../CocoStudio/Armature/utils/CCUtilMath.h  \
    $$PWD/../CocoStudio/Armature/CCArmature.h  \
    $$PWD/../CocoStudio/Armature/CCBone.h  \
    $$PWD/../CocoStudio/Components/CCComAttribute.h  \
    $$PWD/../CocoStudio/Components/CCComAudio.h  \
    $$PWD/../CocoStudio/Components/CCComController.h  \
    $$PWD/../CocoStudio/Components/CCComRender.h  \
    $$PWD/../CocoStudio/Components/CCInputDelegate.h  \
    $$PWD/../CocoStudio/GUI/BaseClasses/UIRootWidget.h  \
    $$PWD/../CocoStudio/GUI/BaseClasses/UIWidget.h  \
    $$PWD/../CocoStudio/GUI/Layouts/UILayoutDefine.h  \
    $$PWD/../CocoStudio/GUI/System/CocosGUI.h  \
    $$PWD/../CocoStudio/GUI/System/UIHelper.h  \
    $$PWD/../CocoStudio/GUI/System/UIInputManager.h  \
    $$PWD/../CocoStudio/GUI/System/UILayer.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/Compatible/CompatibleClasses.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/ScrollWidget/UIListView.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/ScrollWidget/UIPageView.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/ScrollWidget/UIScrollInterface.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/ScrollWidget/UIScrollView.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/UIButton.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/UICheckBox.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/UIImageView.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/UILabel.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/UILabelAtlas.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/UILabelBMFont.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/UILoadingBar.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/UISlider.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/UISwitch.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/UITextField.h  \
    $$PWD/../CocoStudio/Json/CSContentJsonDictionary.h  \
    $$PWD/../CocoStudio/Json/DictionaryHelper.h  \
    $$PWD/../CocoStudio/Json/lib_json/autolink.h  \
    $$PWD/../CocoStudio/Json/lib_json/config.h  \
    $$PWD/../CocoStudio/Json/lib_json/json_features.h  \
    $$PWD/../CocoStudio/Json/lib_json/forwards.h  \
    $$PWD/../CocoStudio/Json/lib_json/json_batchallocator.h  \
    $$PWD/../CocoStudio/Json/lib_json/json_lib.h  \
    $$PWD/../CocoStudio/Json/lib_json/json_tool.h  \
    $$PWD/../CocoStudio/Json/lib_json/reader.h  \
    $$PWD/../CocoStudio/Json/lib_json/value.h  \
    $$PWD/../CocoStudio/Json/lib_json/writer.h  \
    $$PWD/../CocoStudio/Action/CCActionFrame.h  \
    $$PWD/../CocoStudio/Action/CCActionFrameEasing.h  \
    $$PWD/../CocoStudio/Action/CCActionManager.h  \
    $$PWD/../CocoStudio/Action/CCActionNode.h  \
    $$PWD/../CocoStudio/Action/CCActionObject.h  \
    $$PWD/../CocoStudio/GUI/UIWidgets/ScrollWidget/UIListViewEx.h  \
    $$PWD/../CocoStudio/Reader/GUIReader.h  \
    $$PWD/../CocoStudio/GUI/Layouts/UILayout.h  \
    $$PWD/../CocoStudio/GUI/Layouts/UILayoutParameter.h  \
    $$PWD/../CocoStudio/Reader/SceneReader.h  \
    $$PWD/../GUI/CCControlExtension/CCControl.h \
    $$PWD/../GUI/CCControlExtension/CCControlButton.h \
    $$PWD/../GUI/CCControlExtension/CCControlColourPicker.h \
    $$PWD/../GUI/CCControlExtension/CCControlExtensions.h \
    $$PWD/../GUI/CCControlExtension/CCControlHuePicker.h \
    $$PWD/../GUI/CCControlExtension/CCControlPotentiometer.h \
    $$PWD/../GUI/CCControlExtension/CCControlSaturationBrightnessPicker.h \
    $$PWD/../GUI/CCControlExtension/CCControlSlider.h \
    $$PWD/../GUI/CCControlExtension/CCControlStepper.h \
    $$PWD/../GUI/CCControlExtension/CCControlSwitch.h \
    $$PWD/../GUI/CCControlExtension/CCControlUtils.h \
    $$PWD/../GUI/CCControlExtension/CCInvocation.h \
    $$PWD/../GUI/CCControlExtension/CCScale9Sprite.h \
    $$PWD/../GUI/CCEditBox/CCEditBox.h \
    $$PWD/../GUI/CCEditBox/CCEditBoxImpl.h \
    $$PWD/../GUI/CCEditBox/CCEditBoxImplQT.h \
    $$PWD/../GUI/CCScrollView/CCScrollView.h \
    $$PWD/../cocos-ext.h \
    $$PWD/../ExtensionMacros.h \
    $$PWD/../GUI/CCScrollView/CCSorting.h \
    $$PWD/../GUI/CCScrollView/CCTableView.h \
    $$PWD/../GUI/CCScrollView/CCTableViewCell.h \
    $$PWD/../LocalStorage/LocalStorage.h \
    $$PWD/../network/HttpClient.h \
    $$PWD/../network/HttpRequest.h \
    $$PWD/../network/HttpResponse.h \
    $$PWD/../network/Websocket.h \
    $$PWD/../physics_nodes/CCPhysicsDebugNode.h \
    $$PWD/../physics_nodes/CCPhysicsSprite.h \
    $$PWD/../spine/Animation.h \
    $$PWD/../spine/AnimationState.h \
    $$PWD/../spine/AnimationStateData.h \
    $$PWD/../spine/Atlas.h \
    $$PWD/../spine/AtlasAttachmentLoader.h \
    $$PWD/../spine/Attachment.h \
    $$PWD/../spine/AttachmentLoader.h \
    $$PWD/../spine/Bone.h \
    $$PWD/../spine/BoneData.h \
    $$PWD/../spine/CCSkeleton.h \
    $$PWD/../spine/CCSkeletonAnimation.h \
    $$PWD/../spine/extension.h \
    $$PWD/../spine/Json.h \
    $$PWD/../spine/RegionAttachment.h \
    $$PWD/../spine/Skeleton.h \
    $$PWD/../spine/SkeletonData.h \
    $$PWD/../spine/SkeletonJson.h \
    $$PWD/../spine/Skin.h \
    $$PWD/../spine/Slot.h \
    $$PWD/../spine/SlotData.h \
    $$PWD/../spine/spine-cocos2dx.h \
    $$PWD/../spine/spine.h 


SOURCES = \
    $$PWD/../AssetsManager/AssetsManager.cpp \
    $$PWD/../CocoStudio/Armature/CCArmature.cpp \
    $$PWD/../CocoStudio/Armature/CCBone.cpp \
    $$PWD/../CocoStudio/Armature/animation/CCArmatureAnimation.cpp \
    $$PWD/../CocoStudio/Armature/animation/CCProcessBase.cpp \
    $$PWD/../CocoStudio/Armature/animation/CCTween.cpp \
    $$PWD/../CocoStudio/Armature/datas/CCDatas.cpp \
    $$PWD/../CocoStudio/Armature/display/CCBatchNode.cpp \
    $$PWD/../CocoStudio/Armature/display/CCDecorativeDisplay.cpp \
    $$PWD/../CocoStudio/Armature/display/CCDisplayFactory.cpp \
    $$PWD/../CocoStudio/Armature/display/CCDisplayManager.cpp \
    $$PWD/../CocoStudio/Armature/display/CCSkin.cpp \
    $$PWD/../CocoStudio/Armature/physics/CCColliderDetector.cpp \
    $$PWD/../CocoStudio/Armature/utils/CCArmatureDefine.cpp \
    $$PWD/../CocoStudio/Armature/utils/CCArmatureDataManager.cpp \
    $$PWD/../CocoStudio/Armature/utils/CCDataReaderHelper.cpp \
    $$PWD/../CocoStudio/Armature/utils/CCSpriteFrameCacheHelper.cpp \
    $$PWD/../CocoStudio/Armature/utils/CCTransformHelp.cpp \
    $$PWD/../CocoStudio/Armature/utils/CCTweenFunction.cpp \
    $$PWD/../CocoStudio/Armature/utils/CCUtilMath.cpp \
    $$PWD/../CocoStudio/GUI/BaseClasses/UIRootWidget.cpp \
    $$PWD/../CocoStudio/GUI/BaseClasses/UIWidget.cpp \
    $$PWD/../CocoStudio/GUI/Layouts/UILayout.cpp \
    $$PWD/../CocoStudio/GUI/Layouts/UILayoutParameter.cpp \
    $$PWD/../CocoStudio/GUI/Layouts/UILayoutDefine.cpp \
    $$PWD/../CocoStudio/GUI/System/CocosGUI.cpp \
    $$PWD/../CocoStudio/GUI/System/UIHelper.cpp \
    $$PWD/../CocoStudio/GUI/System/UIInputManager.cpp \
    $$PWD/../CocoStudio/GUI/System/UILayer.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/ScrollWidget/UIListViewEx.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/ScrollWidget/UIListView.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/ScrollWidget/UIPageView.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/ScrollWidget/UIScrollView.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/UIButton.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/UICheckBox.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/UIImageView.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/UILabel.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/UILabelAtlas.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/UILabelBMFont.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/UILoadingBar.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/UISlider.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/UISwitch.cpp \
    $$PWD/../CocoStudio/GUI/UIWidgets/UITextField.cpp \
    $$PWD/../CocoStudio/Components/CCComAttribute.cpp \
    $$PWD/../CocoStudio/Components/CCComAudio.cpp \
    $$PWD/../CocoStudio/Components/CCComController.cpp \
    $$PWD/../CocoStudio/Components/CCComRender.cpp \
    $$PWD/../CocoStudio/Components/CCInputDelegate.cpp \
    $$PWD/../CocoStudio/Json/CSContentJsonDictionary.cpp \
    $$PWD/../CocoStudio/Json/DictionaryHelper.cpp \
    $$PWD/../CocoStudio/Json/lib_json/json_value.cpp \
    $$PWD/../CocoStudio/Json/lib_json/json_reader.cpp \
    $$PWD/../CocoStudio/Json/lib_json/json_writer.cpp \
    $$PWD/../CocoStudio/Reader/SceneReader.cpp \
    $$PWD/../CocoStudio/Reader/GUIReader.cpp \
    $$PWD/../CocoStudio/Action/CCActionManager.cpp \
    $$PWD/../CocoStudio/Action/CCActionObject.cpp \
    $$PWD/../CocoStudio/Action/CCActionNode.cpp \
    $$PWD/../CocoStudio/Action/CCActionFrame.cpp \
    $$PWD/../CocoStudio/Action/CCActionFrameEasing.cpp \
    $$PWD/../GUI/CCScrollView/CCScrollView.cpp \
    $$PWD/../GUI/CCScrollView/CCSorting.cpp \
    $$PWD/../GUI/CCScrollView/CCTableView.cpp \
    $$PWD/../GUI/CCScrollView/CCTableViewCell.cpp \
    $$PWD/../GUI/CCControlExtension/CCControlButton.cpp \
    $$PWD/../GUI/CCControlExtension/CCControlColourPicker.cpp \
    $$PWD/../GUI/CCControlExtension/CCControl.cpp \
    $$PWD/../GUI/CCControlExtension/CCControlHuePicker.cpp \
    $$PWD/../GUI/CCControlExtension/CCControlSaturationBrightnessPicker.cpp \
    $$PWD/../GUI/CCControlExtension/CCControlSlider.cpp \
    $$PWD/../GUI/CCControlExtension/CCControlSwitch.cpp \
    $$PWD/../GUI/CCControlExtension/CCControlUtils.cpp \
    $$PWD/../GUI/CCControlExtension/CCInvocation.cpp \
    $$PWD/../GUI/CCControlExtension/CCScale9Sprite.cpp \
    $$PWD/../GUI/CCControlExtension/CCControlPotentiometer.cpp \
    $$PWD/../GUI/CCControlExtension/CCControlStepper.cpp \
    $$PWD/../GUI/CCEditBox/CCEditBox.cpp \
    $$PWD/../GUI/CCEditBox/CCEditBoxImplQT.cpp \
    $$PWD/../network/HttpClient.cpp \
    $$PWD/../physics_nodes/CCPhysicsDebugNode.cpp \
    $$PWD/../physics_nodes/CCPhysicsSprite.cpp \
    $$PWD/../spine/Animation.cpp \
    $$PWD/../spine/AnimationState.cpp \
    $$PWD/../spine/AnimationStateData.cpp \
    $$PWD/../spine/Atlas.cpp \
    $$PWD/../spine/AtlasAttachmentLoader.cpp \
    $$PWD/../spine/Attachment.cpp \
    $$PWD/../spine/AttachmentLoader.cpp \
    $$PWD/../spine/Bone.cpp \
    $$PWD/../spine/BoneData.cpp \
    $$PWD/../spine/Json.cpp \
    $$PWD/../spine/RegionAttachment.cpp \
    $$PWD/../spine/Skeleton.cpp \
    $$PWD/../spine/SkeletonData.cpp \
    $$PWD/../spine/SkeletonJson.cpp \
    $$PWD/../spine/Skin.cpp \
    $$PWD/../spine/Slot.cpp \
    $$PWD/../spine/SlotData.cpp \
    $$PWD/../spine/extension.cpp \
    $$PWD/../spine/spine-cocos2dx.cpp \
    $$PWD/../spine/CCSkeleton.cpp \
    $$PWD/../spine/CCSkeletonAnimation.cpp \
}
}





